AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: |
  The RESTful editing service

Resources:
  EventsTable:
    Type: "AWS::Serverless::SimpleTable"
  CreateDestinationFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: nodejs6.10
      Handler: create.handler
      Policies: AmazonDynamoDBFullAccess
      Environment:
        Variables:
          TABLE_NAME: !Ref EventsTable
      Events:
        CreateDestination:
          Type: Api
          Properties:
            Path: /destination
            Method: POST
