AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: |
  The RESTful editing service

Resources:
  EventsTable:
    Type: "AWS::DynamoDB::Table"
    Properties:
      AttributeDefinitions:
        - AttributeName: EventId
          AttributeType: S
        - AttributeName: StreamName
          AttributeType: S
      KeySchema:
        - AttributeName: EventId
          KeyType: HASH
        - AttributeName: StreamName
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
  CreateDestinationFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: nodejs6.10
      Handler: create.handler
      Timeout: 300
      Policies: AmazonDynamoDBFullAccess
      Environment:
        Variables:
          EVENTS_TABLE: !Ref EventsTable
      Events:
        CreateDestination:
          Type: Api
          Properties:
            Path: /destination
            Method: POST
