AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: |
  The RESTful editing service

Resources:
  ExampleFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: nodejs6.10
      Handler: create.handler
      Events:
        ListCustomers:
          Type: Api
          Properties:
            Path: /destination
            Method: POST
